### ISSUE TITLE
Model Extensions

### ISSUE THREAD

**Issue by yobin-tim** [yobin-tim/mcxs-report#4]
Hi @donotdespair, 

Per our discussion today, I will look to implement the GIG full conditional prior for the $\kappa_+$ parameter for my first extension. I would appreciate any reference material that you can provide to implement this extension. 

For my second extension, I will look to implement the proxy SVAR algorithm. I look forward to reading the Arias et. al paper [here](https://www.sciencedirect.com/science/article/abs/pii/S0304407620303985) and discussing the procedure with you as we go forward.

Thank you!
@yobin-tim

**Comment by donotdespair** [comment]
Hey @yobin-tim 

It was a nice talk! I am looking forward to the developments in your report and afterwards :)

The references:
1. This is the [normal-triple-gamma prior paper](https://www.mdpi.com/2225-1146/8/2/20) It's a bit complicated, but it's great! It it a level of Journal of Econometrics! I don't know why Silvia sent it there!
2. This is the R package: **GIGrvg**

That's to begin with! Good luck!

**Comment by yobin-tim** [comment]
Hi @donotdespair, 

I am leaving a poke here in relation to receiving your feedback on my derivation of the full-conditional posterior of the hyperparameters in my extended model. 

I also wanted to ask if you have any good resources on hyperparameter estimation. I was especially looking to understand how the hyperparameters are calibrated in such models.

I appreciate your help!

**Comment by donotdespair** [comment]
OK @yobin-tim 

I have found the reference to the normal-gamma prior that you are using.

The most relevant paper introducing this type of priors is the one by [Griffin and Brown](https://projecteuclid.org/journals/bayesian-analysis/volume-12/issue-1/Hierarchical-Shrinkage-Priors-for-Regression-Models/10.1214/15-BA990.full) and [these fellows (fantastic statisticians and econometricians)](https://www.mdpi.com/2225-1146/8/2/20) show how far this type of hierarchical modelling can go.

**Comment by yobin-tim** [comment]
Thank you @donotdespair! I will give it a read and then approach you if I have questions.

**Comment by donotdespair** [comment]
Hey @yobin-tim 

Please look at the common SV sampler for structural models in line with what we were talking about.

[SVcommonSF.R.zip](https://github.com/yobin-tim/mcxs-report/files/11785022/SVcommonSF.R.zip)

**Comment by donotdespair** [comment]
Sample code for the `B0_hat` for the normalisation:

```
B0_hat = diag(sign(diag(B0.last_draw))) %*% B0.last_draw
```

**Comment by yobin-tim** [comment]
Thanks @donotdespair! I have implemented the sampler in my model.
